# SPDX-FileCopyrightText: 2025 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: 0BSD

repos:
  - repo: https://github.com/NixOS/nixfmt
    rev: v1.2.0
    hooks:
      - id: nixfmt-nix
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
